import { GalleryItem } from './types';

export const mockGalleryItems: GalleryItem[] = [
{
  id: 1,
  address: '2847 Sunset Boulevard',
  city: 'Los Angeles',
  state: 'CA',
  beds: 5,
  baths: 4,
  sqft: 4200,
  price: '$3,850,000',
  propertyType: 'luxury',
  listingType: 'New Listing',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_114a91a27-1772281138913.png",
  imageAlt: 'Luxurious modern white mansion with large windows and manicured front lawn at sunset',
  createdAt: '2026-03-09',
  downloadCount: 24,
  shareCount: 8,
  template: 'Standard Overlay'
},
{
  id: 2,
  address: '1120 Ocean Drive',
  city: 'Miami Beach',
  state: 'FL',
  beds: 4,
  baths: 3,
  sqft: 3100,
  price: '$2,200,000',
  propertyType: 'luxury',
  listingType: 'Open House',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_13c931287-1772197761303.png",
  imageAlt: 'Contemporary beachfront home with infinity pool overlooking turquoise ocean water',
  createdAt: '2026-03-08',
  downloadCount: 18,
  shareCount: 12,
  template: 'Standard Overlay'
},
{
  id: 3,
  address: '450 Park Avenue, Unit 32B',
  city: 'New York',
  state: 'NY',
  beds: 3,
  baths: 2,
  sqft: 1850,
  price: '$4,500,000',
  propertyType: 'condo',
  listingType: 'New Listing',
  imageUrl: "https://images.unsplash.com/photo-1550575940-ece37cb4e10a",
  imageAlt: 'High-rise luxury condominium building with glass facade reflecting blue sky in Manhattan',
  createdAt: '2026-03-07',
  downloadCount: 31,
  shareCount: 15,
  template: 'Standard Overlay'
},
{
  id: 4,
  address: '789 Malibu Colony Road',
  city: 'Malibu',
  state: 'CA',
  beds: 6,
  baths: 5,
  sqft: 5800,
  price: '$8,900,000',
  propertyType: 'luxury',
  listingType: 'Just Sold',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_1d77ade9b-1773162376685.png",
  imageAlt: 'Sprawling Malibu estate with ocean views, wooden deck, and floor-to-ceiling glass walls',
  createdAt: '2026-03-06',
  downloadCount: 42,
  shareCount: 20,
  template: 'Standard Overlay'
},
{
  id: 5,
  address: '3312 Beverly Glen Circle',
  city: 'Beverly Hills',
  state: 'CA',
  beds: 4,
  baths: 3,
  sqft: 3400,
  price: '$2,750,000',
  propertyType: 'residential',
  listingType: 'Price Reduced',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_139bf5a9b-1773162386845.png",
  imageAlt: 'Traditional Beverly Hills home with red brick facade, lush green lawn, and mature oak trees',
  createdAt: '2026-03-05',
  downloadCount: 9,
  shareCount: 3,
  template: 'Standard Overlay'
},
{
  id: 6,
  address: '5500 Wilshire Blvd, Suite 200',
  city: 'Los Angeles',
  state: 'CA',
  beds: 0,
  baths: 2,
  sqft: 2200,
  price: '$1,100,000',
  propertyType: 'commercial',
  listingType: 'New Listing',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_1ca55c1b9-1773162379676.png",
  imageAlt: 'Modern commercial office building with glass curtain wall exterior on Wilshire Boulevard',
  createdAt: '2026-03-04',
  downloadCount: 7,
  shareCount: 2,
  template: 'Standard Overlay'
},
{
  id: 7,
  address: '1800 Canyon Road',
  city: 'Santa Fe',
  state: 'NM',
  beds: 3,
  baths: 2,
  sqft: 2600,
  price: '$985,000',
  propertyType: 'residential',
  listingType: 'New Listing',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_182083eab-1773162384502.png",
  imageAlt: 'Adobe-style Santa Fe home with terracotta walls, wooden vigas, and desert landscape garden',
  createdAt: '2026-03-03',
  downloadCount: 14,
  shareCount: 6,
  template: 'Standard Overlay'
},
{
  id: 8,
  address: '220 Lake Shore Drive, Unit 15A',
  city: 'Chicago',
  state: 'IL',
  beds: 2,
  baths: 2,
  sqft: 1400,
  price: '$875,000',
  propertyType: 'condo',
  listingType: 'Open House',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_1685751cb-1773162384642.png",
  imageAlt: 'Elegant Chicago lakefront condo building with art deco architecture and Lake Michigan views',
  createdAt: '2026-03-01',
  downloadCount: 11,
  shareCount: 5,
  template: 'Standard Overlay'
},
{
  id: 9,
  address: '9401 Sunset Strip',
  city: 'West Hollywood',
  state: 'CA',
  beds: 4,
  baths: 4,
  sqft: 3800,
  price: '$3,200,000',
  propertyType: 'luxury',
  listingType: 'New Listing',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_1c8174f62-1773162379676.png",
  imageAlt: 'Ultra-modern West Hollywood hillside home with rooftop terrace and panoramic city views at night',
  createdAt: '2026-02-28',
  downloadCount: 28,
  shareCount: 11,
  template: 'Standard Overlay'
},
{
  id: 10,
  address: '640 Pacific Coast Highway',
  city: 'Laguna Beach',
  state: 'CA',
  beds: 3,
  baths: 3,
  sqft: 2900,
  price: '$4,100,000',
  propertyType: 'luxury',
  listingType: 'Just Sold',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_121df3ace-1773162385061.png",
  imageAlt: 'Coastal Laguna Beach residence with white stucco exterior, blue shutters, and ocean-facing balcony',
  createdAt: '2026-02-25',
  downloadCount: 36,
  shareCount: 17,
  template: 'Standard Overlay'
},
{
  id: 11,
  address: '3050 Brickell Avenue',
  city: 'Miami',
  state: 'FL',
  beds: 2,
  baths: 2,
  sqft: 1600,
  price: '$1,350,000',
  propertyType: 'condo',
  listingType: 'Price Reduced',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_105e583f2-1773162382465.png",
  imageAlt: 'Sleek Brickell Avenue luxury condo tower with curved glass balconies overlooking Biscayne Bay',
  createdAt: '2026-02-20',
  downloadCount: 5,
  shareCount: 1,
  template: 'Standard Overlay'
},
{
  id: 12,
  address: '7700 Mulholland Drive',
  city: 'Los Angeles',
  state: 'CA',
  beds: 5,
  baths: 5,
  sqft: 6200,
  price: '$7,500,000',
  propertyType: 'luxury',
  listingType: 'New Listing',
  imageUrl: "https://img.rocket.new/generatedImages/rocket_gen_img_1d285651a-1773162380415.png",
  imageAlt: 'Dramatic Mulholland Drive estate with infinity pool, city light views, and contemporary architecture',
  createdAt: '2026-02-15',
  downloadCount: 19,
  shareCount: 9,
  template: 'Standard Overlay'
}];